version: '3.7'

services:
  iauditor-exporter:
    image: eddabrahamsen/iauditor-exporter:latest
    container_name: iauditor-exporter
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - 'format=sql actions-sql'
      - CONFIG_NAME=iauditor
      - API_TOKEN=
      - SYNC_DELAY_IN_SECONDS=900
      - MEDIA_SYNC_OFFSET_IN_SECONDS=900
      - TEMPLATE_IDS=
      - SQL_TABLE=iauditor_data
      - DB_TYPE=mssql+pyodbc_mssql
      - DB_USER=
      - DB_PWD=
      - DB_SERVER=
      - DB_PORT=1433
      - DB_NAME=iAuditor?driver=ODBC Driver 17 for SQL Server
      - DB_SCHEMA=dbo
      - USE_REAL_TEMPLATE_NAME=false
      - EXPORT_ARCHIVED=false
      - EXPORT_COMPLETED=both
      - MERGE_ROWS=false
      - ACTIONS_MERGE_ROWS=false
      - ALLOW_TABLE_CREATION=false
    volumes:
      - type: bind
        source: ./last_successful
        target: /app/last_successful
      - type: bind
        source: ./exports
        target: /app/exports
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - iauditor_portainer_data:/data
volumes:
  iauditor_portainer_data: