API:
    token: YOUR-API-TOKEN-HERE
config_name: test
export_options:
    export_path:
    timezone:
    filename:
    export_archived: false
    export_completed: both
    use_real_template_name: false
    csv_options:
        export_inactive_items: false
    export_profiles:
    template_ids: 
    sync_delay_in_seconds: 70
    media_sync_offset_in_seconds: 0
    allow_table_creation: true
    merge_rows: true
    sql_table: iauditor_data
    database_type: mssql+pyodbc_mssql
    database_user: 
    database_pwd: 
    database_server: 
    database_port: 1433
    database_schema: 
    database_name: iAuditor?driver=ODBC Driver 17 for SQL Server
