# yamllint disable rule:line-length
---
name: goreleaser

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Fech
        run: git fetch --force --tags

      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          cache: true

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> .release-env

      - name: Prepare Safe Directory
        run: git config --global --add safe.directory /home/runner/work/safetyculture-exporter/safetyculture-exporter

      - name: Run GoReleaser
        run: make release
