# yamllint disable rule:line-length
---
name: goreleaser

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        run: make release github_token=${{ secrets.GITHUB_TOKEN }}
