// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CheckApiKey():Promise<boolean>;

export function ExportCSV():Promise<void>;

export function GetSettings():Promise<api.ExporterConfiguration>;

export function Greet(arg1:string):Promise<string>;

export function ValidateApiKey(arg1:string):Promise<boolean>;
