// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckApiKey() {
  return window['go']['main']['App']['CheckApiKey']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ValidateApiKey(arg1) {
  return window['go']['main']['App']['ValidateApiKey'](arg1);
}
